package Tampilan;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import kelas.user;

/**
 *
 * @author MyBook Hype
 */
public class FrameUser extends javax.swing.JFrame {

    /**
     * Creates new form FrameUser
     */
    public FrameUser() {
        initComponents();
        loadTabel();
        reset();
    }

    void loadTabel() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("User Name");
        model.addColumn("Email");
        model.addColumn("Full Name");
        model.addColumn("Status");

        try {
            user us = new user();
            ResultSet data = us.tampilUser();

            while (data.next()) {
                model.addRow(new Object[]{
                    data.getString("user_name"),
                    data.getString("user_email"),
                    data.getString("user_fullname"),
                    data.getInt("user_status") == 1 ? "Aktif" : "Non Aktif"
                });
            }
        } catch (SQLException sQLException) {
        }
        Tuser.setModel(model);
    }

    void reset() {
        Tusername.setText(null);
        Tusername.setEditable(true);
        Temail.setText(null);
        Tpassword.setText(null);
        Tfullname.setText(null);
        Tstatus.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tusername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Tstatus = new javax.swing.JComboBox<>();
        Temail = new javax.swing.JTextField();
        Tpassword = new javax.swing.JTextField();
        Tfullname = new javax.swing.JTextField();
        Ttambah = new javax.swing.JButton();
        Thapus = new javax.swing.JButton();
        Tubah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tuser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TusernameActionPerformed(evt);
            }
        });
        getContentPane().add(Tusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 58, 142, -1));

        jLabel2.setText("User Name        :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 61, -1, -1));

        jLabel3.setText("Email                 :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 107, -1, -1));

        jLabel4.setText("Password          :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 152, -1, -1));

        jLabel5.setText("FullName          :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 194, -1, -1));

        jLabel6.setText("Status               :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 240, -1, -1));

        Tstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Non Aktif" }));
        getContentPane().add(Tstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 237, 142, -1));

        Temail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemailActionPerformed(evt);
            }
        });
        getContentPane().add(Temail, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 104, 142, -1));
        getContentPane().add(Tpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 149, 142, -1));
        getContentPane().add(Tfullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 191, 142, -1));

        Ttambah.setText("Tambah");
        Ttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtambahActionPerformed(evt);
            }
        });
        getContentPane().add(Ttambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 455, -1, -1));

        Thapus.setText("Hapus");
        Thapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThapusActionPerformed(evt);
            }
        });
        getContentPane().add(Thapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 455, -1, -1));

        Tubah.setText("Ubah");
        Tubah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TubahMouseClicked(evt);
            }
        });
        Tubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TubahActionPerformed(evt);
            }
        });
        getContentPane().add(Tubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 455, -1, -1));

        Tuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TuserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tuser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 15, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("FrameUser");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 6, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TemailActionPerformed

    private void TusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TusernameActionPerformed

    private void ThapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThapusActionPerformed
        try {
            user usr = new user();
            usr.setUser_name(Tusername.getText());
            usr.hapusUser();
        } catch (SQLException sQLException) {
        }
        loadTabel();
        reset();

    }//GEN-LAST:event_ThapusActionPerformed

    private void TuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TuserMouseClicked
        int baris = Tuser.rowAtPoint(evt.getPoint());
        String userName = Tuser.getValueAt(baris, 0).toString();
        String email = Tuser.getValueAt(baris, 1).toString();
        String fullname = Tuser.getValueAt(baris, 2).toString();
        String status = Tuser.getValueAt(baris, 3).toString();

        Tusername.setText(userName);
        Tusername.setEditable(false);
        Temail.setText(email);
        Tfullname.setText(fullname);
        Tstatus.setSelectedItem(status);
    }//GEN-LAST:event_TuserMouseClicked

    private void TubahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TubahMouseClicked

    }//GEN-LAST:event_TubahMouseClicked

    private void TtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtambahActionPerformed
        try {

            user user = new user();
            user.setUser_name(Tusername.getText());
            user.setUser_email(Temail.getText());
            user.setUser_password(Tpassword.getText());
            user.setUser_fullname(Tfullname.getText());
            if (Tstatus.getSelectedItem().equals("Aktif")) {
                user.setUser_status(1);
            } else {
                user.setUser_status(0);
            }
            user.tambahUser();
        } catch (SQLException sQLException) {

        }
        loadTabel();
        reset();


    }//GEN-LAST:event_TtambahActionPerformed

    private void TubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TubahActionPerformed

            try {
            user usr = new user();
            usr.setUser_name(Tusername.getText());
            usr.setUser_email(Temail.getText());
            usr.setUser_password(Tpassword.getText());
            usr.setUser_fullname(Tfullname.getText());
            if (Tstatus.getSelectedItem().equals("Aktif")) {
                usr.setUser_status(1);
            } else {
                usr.setUser_status(0);
            }
            usr.ubahUser();
            
        } catch (SQLException sQLException) {
        }
        loadTabel();
        reset();
    }//GEN-LAST:event_TubahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Temail;
    private javax.swing.JTextField Tfullname;
    private javax.swing.JButton Thapus;
    private javax.swing.JTextField Tpassword;
    private javax.swing.JComboBox<String> Tstatus;
    private javax.swing.JButton Ttambah;
    private javax.swing.JButton Tubah;
    private javax.swing.JTable Tuser;
    private javax.swing.JTextField Tusername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
