package Tampilan;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import KELAS.Category;
import kelas.Product;

public class FrameProduct extends javax.swing.JFrame {

    /**
     * Creates new form FrameProduct
     */
    public FrameProduct() {
        initComponents();
        loadtabel();
        autoID();
        comboCategory();
    }
    void loadtabel(){
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("id product");
        model.addColumn("nama product");
        model.addColumn("deskripsi");
        model.addColumn("harga");
        model.addColumn("category");
        
        try {
            Product prd=new Product();
            ResultSet data=prd.tampilProduk();
            while (data.next()){
                model.addRow(new Object[]{
                    data.getString("produk_id"),
                    data.getString("produk_name"),
                    data.getString("produk_desc"),
                    data.getString("produk_price"),
                    data.getString("category_name"),});
                }
            }catch(SQLException sQLException){
                
        }
        Tproduk.setModel(model);
    }
    void comboCategory(){
        try{
        Category cat = new Category();
        ResultSet data = cat.tampilComboBox();
        
        while (data.next()){
            String isi = data.getString("category_name");
            Tkat.addItem(isi);
        }
    }catch (SQLException ex){
        Logger.getLogger(FrameProduct.class.getName()).log(Level.SEVERE,null, ex);
    }
    }
    void autoID(){
        try{
            Product prod = new Product();
            ResultSet id = prod.autoID();
            
             if (id.next()){
                 int auto = id.getInt("produk_id")+1;
                 Tid.setText(String.valueOf(auto));
                 
             }else{
                 Tid.setText("1");
             }
             Tid.setEditable(false);
        }catch(SQLException sQLException){
        }
    }
    void reset(){
        
        autoID();
        Tnama.setText(null);
        Tdes.setText(null);
        Tharga.setText(null);
        Tkat.setSelectedItem(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tproduk = new javax.swing.JTable();
        Tkat = new javax.swing.JComboBox<>();
        Ttambah = new javax.swing.JButton();
        Tid = new javax.swing.JTextField();
        Tnama = new javax.swing.JTextField();
        Tdes = new javax.swing.JTextField();
        Tharga = new javax.swing.JTextField();
        Thapus = new javax.swing.JButton();
        Tubah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FrameProduct");

        jLabel2.setText("ID");

        jLabel3.setText("Nama");

        jLabel4.setText("Deskripsi");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setText("Harga");

        jLabel6.setText("Kategori");

        Tproduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tproduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TprodukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tproduk);

        Tkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TkatActionPerformed(evt);
            }
        });

        Ttambah.setText("Tambah");
        Ttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtambahActionPerformed(evt);
            }
        });

        Tdes.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Tdes.setDragEnabled(true);

        Thapus.setText("Hapus");
        Thapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThapusActionPerformed(evt);
            }
        });

        Tubah.setText("Ubah");
        Tubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TubahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(Thapus)
                                .addGap(44, 44, 44)
                                .addComponent(Tubah))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Tkat, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Tharga, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Tdes, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                            .addComponent(Tid)
                                            .addComponent(Tnama)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(Ttambah)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Tid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Tnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tdes, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Tharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Tkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ttambah)
                            .addComponent(Thapus)
                            .addComponent(Tubah))
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TkatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TkatActionPerformed

    private void TtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtambahActionPerformed
        // TODO add your handling code here:
        try {
            Product prod = new Product();
            Category cat = new Category();
            prod.setProduct_id(Integer.parseInt(Tid.getText()));
            prod.setProduct_name(Tnama.getText());
            prod.setProduct_desc(Tdes.getText());
            prod.setProduct_price(Integer.parseInt(Tharga.getText()));
            String selectedCategory = (String) Tkat.getSelectedItem();
            cat.setCategory_name(Tkat.getSelectedItem().toString());
            ResultSet data = cat.Konversi();

            if (data.next()) {
                String isi = data.getString("category_id");
                prod.setProduct_cat_id(Integer.parseInt(isi));
            }

            prod.tambahProduct();
        } catch (SQLException sQLException) {
            System.out.println("Data tidak masuk");
        }
        loadtabel();
        reset();
    }//GEN-LAST:event_TtambahActionPerformed

    private void ThapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThapusActionPerformed
        // TODO add your handling code here:
        try {
            Product prod = new Product();
            prod.setProduct_id(Integer.parseInt(Tid.getText()));
            prod.hapusProduk();
        } catch (SQLException sQLException) {
        }
        loadtabel();
        reset();
    }//GEN-LAST:event_ThapusActionPerformed

    private void TubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TubahActionPerformed
        try {
            Product prod = new Product();
            Category cat = new Category();
            prod.setProduct_id(Integer.parseInt(Tid.getText()));
            prod.setProduct_name(Tnama.getText());
            prod.setProduct_desc(Tdes.getText());
            prod.setProduct_price(Integer.parseInt(Tharga.getText()));
            String selectedCategory = (String) Tkat.getSelectedItem();
            cat.setCategory_name(Tkat.getSelectedItem().toString());
            ResultSet data = cat.Konversi();

            if (data.next()) {
                String isi = data.getString("category_id");
                prod.setProduct_cat_id(Integer.parseInt(isi));
            }

            prod.ubahProduct();
        } catch (SQLException sQLException) {
            System.out.println("Data tidak masuk");
        }
        loadtabel();
        reset();
    }//GEN-LAST:event_TubahActionPerformed

    private void TprodukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TprodukMouseClicked
        // TODO add your handling code here:
        int baris = Tproduk.rowAtPoint(evt.getPoint());
        String productID = Tproduk.getValueAt(baris, 0).toString();
        String productName = Tproduk.getValueAt(baris, 1).toString();
        String productDesc = Tproduk.getValueAt(baris, 2).toString();
        String productPrice = Tproduk.getValueAt(baris, 3).toString();
        String productCat = Tproduk.getValueAt(baris, 4).toString();

        Tid.setText(productID);
        Tid.setEditable(false);
        Tnama.setText(productName);
        Tdes.setText(productDesc);
        Tharga.setText(productPrice);
        Tkat.setSelectedItem(productCat);
    }//GEN-LAST:event_TprodukMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Tdes;
    private javax.swing.JButton Thapus;
    private javax.swing.JTextField Tharga;
    private javax.swing.JTextField Tid;
    private javax.swing.JComboBox<String> Tkat;
    private javax.swing.JTextField Tnama;
    private javax.swing.JTable Tproduk;
    private javax.swing.JButton Ttambah;
    private javax.swing.JButton Tubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
